services:
  dns_checker:
    image: charly3012/dns-checker:latest
    #build: .
    container_name: dns-checker
    restart: unless-stopped

    volumes:
    - ./path/to/config.json:/app/config.json #See config-example.json to configure application


